# Generated by Django 3.0 on 2019-12-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('amount_sold', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.Pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.PizzaType'),
        ),
    ]
