# Generated by Django 3.0 on 2019-12-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_type_id',
            new_name='pizza_type',
        ),
    ]
